@baseUrl = http://localhost:4004/odata/v4
@UUID = afb808af-bd9c-42a4-a290-51d4375f87c8

### Create
POST {{baseUrl}}/catalog/Students HTTP/1.1
Content-Type: application/json

{ "firstName": "John", "lastName": "Wayne", "email": "john.wayne@example.com", "age": 21}

### Read
GET {{baseUrl}}/catalog/Students HTTP/1.1

### Update
PATCH {{baseUrl}}/catalog/Students(ID='{{UUID}}') HTTP/1.1
Content-Type: application/json

{ "age": 12 }

### Delete
DELETE {{baseUrl}}/catalog/Students(ID='{{UUID}}') HTTP/1.1